# railway.toml
[build]
builder = "nixpacks"
buildCommand = "cd frontend && npm install && npm run build"

[deploy]
startCommand = "cd backend && python app.py"
healthcheckPath = "/"
healthcheckTimeout = 100